### ISSUE TITLE
Zabbix 7 - Cannot Import YAML

### ISSUE THREAD

**Issue by stevefxp1** [intellitrend/intellitrend-mobile-zabbix-mediatype#1]
Hello all,

This is a new Zabbix 7 implementation. When I import the YAML I am getting an error saying no changes. 

Thanks,
Steve

![Screenshot 2024-07-12 151133](https://github.com/user-attachments/assets/b8cf1d81-227a-4d13-9a2c-cf101cbb9b93)
![Screenshot 2024-07-12 151142](https://github.com/user-attachments/assets/1f821a23-7405-433b-85b2-1a8ed2bf0d1c)

**Comment by intellitrend-team** [comment]
Hello Steve, that message means that the currently installed IntelliTrend Mobile media type isn't functionally different to the export, so there is nothing to do. It should be ready for push notifications.

**Comment by stevefxp1** [comment]
Thats the problem...there is no media type YAML installed yet. This is a brand new v7 installation. I should not be getting this message.

**Comment by intellitrend-team** [comment]
Ah, I see the issue. You have to go to "Alerts" -> "Media types" first, then you can import the YAML file. The message is a bit misleading, it didn't import the media type because the YAML file doesn't contain any templates and the templates page can only import templates.

**Comment by stevefxp1** [comment]
Ding ding ding...thank you. I was getting nuts trying to understand why this was not working.Sent from my T-Mobile 5G Device
-------- Original message --------From: IntelliTrend Team ***@***.***> Date: 7/15/24  09:24  (GMT-05:00) To: intellitrend/intellitrend-mobile-zabbix-mediatype ***@***.***> Cc: stevefxp1 ***@***.***>, Author ***@***.***> Subject: Re: [intellitrend/intellitrend-mobile-zabbix-mediatype] Zabbix 7 - Cannot Import YAML (Issue #1) 
Ah, I see the issue. You have to go to "Alerts" -> "Media types" first, then you can import the YAML file. The message is a bit misleading, it didn't import the media type because the YAML file doesn't contain any templates and the templates page can only import templates.

**Comment by intellitrend-team** [comment]
Good to know it's working now! If you have any more problems, feel free to create another issue.
